// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function toSerializableError(error, errorCode) {
  return /* record */[
          /* message */error[/* message */0],
          /* name */error[/* name */1],
          /* stack */error[/* stack */2],
          /* code */errorCode
        ];
}

export {
  toSerializableError ,
  
}
/* No side effect */
