// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Hub from "../aws/Hub.bs.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function logger(str) {
  console.log(str);
  return /* () */0;
}

function fromJs(payloadJs) {
  return /* record */[
          /* event */payloadJs.event,
          /* data */payloadJs.data,
          /* message */Caml_option.undefined_to_opt(payloadJs.message)
        ];
}

function listener(payload) {
  console.log("payload", payload);
  var match = payload[/* event */0];
  switch (match) {
    case "configured" :
        console.log("the Auth module is configured");
        return /* () */0;
    case "signIn" :
        console.log("user signed in");
        return /* () */0;
    case "signIn_failure" :
        console.log("user sign in failed");
        return /* () */0;
    case "signOut" :
        console.log("user signed out");
        return /* () */0;
    case "signUp" :
        console.log("user signed up");
        return /* () */0;
    default:
      console.log("unknown error");
      return /* () */0;
  }
}

Hub.listen("auth", listener);

export {
  logger ,
  fromJs ,
  listener ,
  
}
/*  Not a pure module */
