// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Antd from "antd";
import * as React from "react";
import * as Antd_Icon from "@schero/bs-antd/src/Antd_Icon.bs.js";
import * as RouterLinks from "./RouterLinks.bs.js";

function Nav(Props) {
  var current = Props.current;
  return React.createElement("div", undefined, React.createElement(Antd.Menu, {
                  mode: "horizontal",
                  selectedKeys: /* array */[current],
                  children: null
                }, React.createElement(Antd.Menu.Item, {
                      key: "home",
                      children: React.createElement(RouterLinks.NavLink.make, {
                            href: "/",
                            children: null
                          }, React.createElement(Antd_Icon.make, {
                                icon: /* home */-988624353
                              }), "Home")
                    }), React.createElement(Antd.Menu.Item, {
                      key: "profile",
                      children: React.createElement(RouterLinks.NavLink.make, {
                            href: "/profile",
                            children: null
                          }, React.createElement(Antd_Icon.make, {
                                icon: /* profile */-213300951
                              }), "Profile")
                    }), React.createElement(Antd.Menu.Item, {
                      key: "protected",
                      children: React.createElement(RouterLinks.NavLink.make, {
                            href: "/protected",
                            children: null
                          }, React.createElement(Antd_Icon.make, {
                                icon: /* profile */-213300951
                              }), "Protected")
                    })));
}

var make = Nav;

export {
  make ,
  
}
/* antd Not a pure module */
