// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Nav from "./Nav.bs.js";
import * as React from "react";
import * as Public from "../pages/Public.bs.js";
import * as Profile from "../pages/Profile.bs.js";
import * as Protected from "../pages/Protected.bs.js";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";

function str(prim) {
  return prim;
}

function Router(Props) {
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  var match = url[/* path */0];
  var current;
  if (match) {
    switch (match[0]) {
      case "profile" :
          current = match[1] ? "public" : "profile";
          break;
      case "signin" :
          current = match[1] ? "public" : "signin";
          break;
      case "signup" :
          current = match[1] ? "public" : "signup";
          break;
      default:
        current = "public";
    }
  } else {
    current = "public";
  }
  var match$1 = url[/* path */0];
  var tmp;
  var exit = 0;
  if (match$1) {
    switch (match$1[0]) {
      case "profile" :
          if (match$1[1]) {
            exit = 1;
          } else {
            tmp = React.createElement(Profile.make, { });
          }
          break;
      case "protected" :
          if (match$1[1]) {
            exit = 1;
          } else {
            tmp = React.createElement(Protected.make, { });
          }
          break;
      default:
        exit = 1;
    }
  } else {
    tmp = React.createElement(Public.make, { });
  }
  if (exit === 1) {
    tmp = React.createElement(Public.make, { });
  }
  return React.createElement(React.Fragment, undefined, React.createElement(Nav.make, {
                  current: current
                }), React.createElement("main", undefined, React.createElement("div", {
                      className: "task-container"
                    }, tmp)));
}

var make = Router;

var $$default = Router;

export {
  str ,
  make ,
  $$default ,
  $$default as default,
  
}
/* Nav Not a pure module */
