// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_List from "bs-platform/lib/es6/belt_List.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";

function handleClick($$event) {
  if ($$event.defaultPrevented) {
    return 0;
  } else {
    $$event.preventDefault();
    var anchor = $$event.currentTarget;
    return ReasonReactRouter.push(anchor.href);
  }
}

function RouterLinks$Link(Props) {
  var href = Props.href;
  var className = Props.className;
  var children = Props.children;
  var tmp = {
    href: href,
    onClick: handleClick
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("a", tmp, children);
}

var Link = {
  handleClick: handleClick,
  make: RouterLinks$Link
};

function RouterLinks$NavLink(Props) {
  var href = Props.href;
  var children = Props.children;
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  var isActive = Belt_List.length(Belt_List.keep(url[/* path */0], (function (p) {
              return href.includes(p);
            }))) > 0;
  return React.createElement(RouterLinks$Link, {
              href: href,
              className: "nav-link" + (
                isActive ? " nav-link--active" : ""
              ),
              children: children
            });
}

var NavLink = {
  make: RouterLinks$NavLink
};

export {
  Link ,
  NavLink ,
  
}
/* react Not a pure module */
