// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function formTypeToString(param) {
  switch (param) {
    case /* SignIn */0 :
        return "Sign In";
    case /* SignUp */1 :
        return "Sign Up";
    case /* ConfirmSignUp */2 :
        return "Confirm Sign Up";
    case /* ForgotPassword */3 :
        return "Forgot Password";
    case /* ForgotPasswordSubmit */4 :
        return "forgotPasswordSubmit";
    
  }
}

function fromJsAttrs(attributes) {
  return /* record */[
          /* sub */attributes.sub,
          /* email_verified */attributes.email_verified,
          /* email */attributes.email,
          /* phone_number */attributes.phone_number
        ];
}

function fromJs(data) {
  return /* record */[
          /* username */data.username,
          /* attributes */fromJsAttrs(data.attributes)
        ];
}

export {
  formTypeToString ,
  fromJsAttrs ,
  fromJs ,
  
}
/* No side effect */
