// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function valueFromEvent(evt) {
  return evt.target.value;
}

function nameFromEvent(evt) {
  return evt.target.name;
}

export {
  valueFromEvent ,
  nameFromEvent ,
  
}
/* No side effect */
