// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Container from "../components/Container.bs.js";
import * as FormStyle from "./FormStyle.bs.js";
import * as FormTypes from "../hooks/FormTypes.bs.js";

function FormContainer(Props) {
  var formType = Props.formType;
  var onClick = Props.onClick;
  return React.createElement(Container.make, {
              children: null
            }, React.createElement("h1", undefined, FormTypes.formTypeToString(formType)), React.createElement("button", {
                  className: FormStyle.Styles.button,
                  onClick: onClick
                }, "Change Form"));
}

var make = FormContainer;

export {
  make ,
  
}
/* react Not a pure module */
