// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Container from "../components/Container.bs.js";
import * as ProtectedRoute from "./ProtectedRoute.bs.js";

function Protected(Props) {
  ProtectedRoute.useProtectedRoute(/* () */0);
  return React.createElement(Container.make, {
              children: React.createElement("h1", undefined, "Protected route")
            });
}

var make = Protected;

export {
  make ,
  
}
/* react Not a pure module */
