// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as FormStyle from "../pages/FormStyle.bs.js";

function ForgotPasswordSubmit(Props) {
  Props.formType;
  var onClick = Props.onClick;
  var onChange = Props.onChange;
  return React.createElement("div", {
              className: FormStyle.Styles.container
            }, React.createElement("input", {
                  className: FormStyle.Styles.input,
                  name: "username",
                  placeholder: "Username",
                  type: "username",
                  onChange: onChange
                }), React.createElement("input", {
                  className: FormStyle.Styles.input,
                  name: "confirmationCode",
                  placeholder: "Confirmation Code",
                  type: "confirmationCode",
                  onChange: onChange
                }), React.createElement("input", {
                  className: FormStyle.Styles.input,
                  name: "password",
                  placeholder: "New password",
                  type: "password",
                  onChange: onChange
                }), React.createElement("button", {
                  className: FormStyle.Styles.button,
                  onClick: onClick
                }, "Save new password"));
}

var make = ForgotPasswordSubmit;

export {
  make ,
  
}
/* react Not a pure module */
