// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as React from "react";

var container = Css.style(/* :: */[
      Css.marginTop(Css.px(0)),
      /* :: */[
        Css.marginBottom(/* auto */-1065951377),
        /* :: */[
          Css.paddingTop(Css.px(50)),
          /* :: */[
            Css.paddingBottom(Css.px(100)),
            /* [] */0
          ]
        ]
      ]
    ]);

var Styles = {
  container: container
};

function Container(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: container
            }, children);
}

var make = Container;

var $$default = Container;

export {
  Styles ,
  make ,
  $$default ,
  $$default as default,
  
}
/* container Not a pure module */
