// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as React from "react";

var button = Css.style(/* :: */[
      Css.backgroundColor(/* `hex */[
            5194459,
            "#006bfc"
          ]),
      /* :: */[
        Css.color(Css.white),
        /* :: */[
          Css.width(Css.px(316)),
          /* :: */[
            Css.height(Css.px(45)),
            /* :: */[
              Css.fontWeight(/* `num */[
                    5496390,
                    600
                  ]),
              /* :: */[
                Css.fontSize(Css.px(14)),
                /* :: */[
                  Css.cursor(/* pointer */-786317123),
                  /* :: */[
                    Css.borderStyle(/* none */-922086728),
                    /* :: */[
                      Css.outlineStyle(/* none */-922086728),
                      /* :: */[
                        Css.borderRadius(Css.px(3)),
                        /* :: */[
                          Css.marginTop(Css.px(25)),
                          /* :: */[
                            Css.boxShadow(Css.Shadow.box(Css.px(0), Css.px(1), Css.px(3), undefined, undefined, Css.rgba(0, 0, 0, 0.3))),
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var Styles = {
  button: button
};

function Button(Props) {
  var onClick = Props.onClick;
  var title = Props.title;
  return React.createElement("button", {
              className: button,
              type: "submit",
              onClick: (function (_evt) {
                  return onClick;
                })
            }, title);
}

var make = Button;

var $$default = Button;

export {
  Styles ,
  make ,
  $$default ,
  $$default as default,
  
}
/* button Not a pure module */
