// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";

var container = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.flexDirection(Css.column),
        /* :: */[
          Css.marginTop(Css.px(150)),
          /* :: */[
            Css.justifyContent(Css.center),
            /* :: */[
              Css.alignItems(Css.center),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var input = Css.style(/* :: */[
      Css.height(Css.px(45)),
      /* :: */[
        Css.marginTop(Css.px(8)),
        /* :: */[
          Css.width(Css.px(300)),
          /* :: */[
            Css.maxWidth(Css.px(300)),
            /* :: */[
              Css.paddingTop(Css.px(0)),
              /* :: */[
                Css.paddingBottom(Css.px(8)),
                /* :: */[
                  Css.alignItems(Css.center),
                  /* :: */[
                    Css.fontSize(Css.px(16)),
                    /* :: */[
                      Css.outlineStyle(Css.none),
                      /* :: */[
                        Css.borderStyle(Css.none),
                        /* :: */[
                          Css.fontSize(Css.px(16)),
                          /* :: */[
                            Css.borderBottom(Css.px(2), Css.solid, Css.rgba(0, 0, 0, 0.3)),
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var toggleForm = Css.style(/* :: */[
      Css.fontWeight(/* `num */[
            5496390,
            600
          ]),
      /* :: */[
        Css.marginTop(Css.px(8)),
        /* :: */[
          Css.paddingTop(Css.px(0)),
          /* :: */[
            Css.paddingBottom(Css.px(25)),
            /* :: */[
              Css.marginTop(Css.px(15)),
              /* :: */[
                Css.marginBottom(Css.px(0)),
                /* :: */[
                  Css.textAlign(Css.center),
                  /* :: */[
                    Css.fontSize(Css.px(16)),
                    /* :: */[
                      Css.outlineStyle(Css.none),
                      /* :: */[
                        Css.borderStyle(Css.none),
                        /* :: */[
                          Css.fontSize(Css.px(16)),
                          /* :: */[
                            Css.color(Css.rgba(0, 0, 0, 0.6)),
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var resetPassword = Css.style(/* :: */[
      Css.marginTop(Css.px(5)),
      /* [] */0
    ]);

var anchor = Css.style(/* :: */[
      Css.color(/* `hex */[
            5194459,
            "#006bfc"
          ]),
      /* :: */[
        Css.cursor(/* pointer */-786317123),
        /* [] */0
      ]
    ]);

var Styles = {
  container: container,
  input: input,
  toggleForm: toggleForm,
  resetPassword: resetPassword,
  anchor: anchor
};

export {
  Styles ,
  
}
/* container Not a pure module */
