// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Container from "./Container.bs.js";

function Public(Props) {
  return React.createElement(Container.make, {
              children: React.createElement("h1", undefined, "Public route")
            });
}

var make = Public;

var $$default = Public;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
