// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Router from "./router/Router.bs.js";
import * as Amplify from "./aws/Amplify.bs.js";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ServiceWorker from "./serviceWorker";
import * as IndexModuleCss from "./index.module.css";

Amplify.configure(Amplify.Config.awsConfig);

var _css = IndexModuleCss;

((require('antd/dist/antd.css')));

function register_service_worker(prim) {
  ServiceWorker.register();
  return /* () */0;
}

function unregister_service_worker(prim) {
  ServiceWorker.unregister();
  return /* () */0;
}

ReactDOMRe.renderToElementWithId(React.createElement(Router.make, { }), "root");

export {
  _css ,
  register_service_worker ,
  unregister_service_worker ,
  
}
/*  Not a pure module */
