// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as AwsAmplify from "aws-amplify";
import * as AwsExportsJs from "../../src/aws-exports.js";

var awsConfig = AwsExportsJs.default;

console.log("awsConfig", awsConfig);

function configure(param) {
  AwsAmplify.default.configure(awsConfig);
  return /* () */0;
}

export {
  awsConfig ,
  configure ,

}
/* awsConfig Not a pure module */
